/*
 * Photons.cpp
 *
 *  Created on: Oct 28, 2013
 *      Author: philip
 */

#include "../../interface/Objects/Photons.h"

namespace std {

Photons::Photons() {
	// TODO Auto-generated constructor stub
	objName = "Photons";
}

Photons::~Photons() {
	// TODO Auto-generated destructor stub
}

void Photons::allPlots(AllSamples samples){

	Variable photon_pt("Photon_ET", "Photon E_{T} [GeV]", 0, 150, 2);
	Variable photon_eta("Photon_Eta", "Photon #eta", -3., 3., 10);
	Variable photon_abseta("Photon_AbsEta", "Photon |#eta|", 0., 3., 10);
	Variable photon_sigmaietaieta_barrel("Photon_sigma_ietaieta_barrel", "#sigmai#etai#eta(barrel)", 0., 0.03, 10);
	Variable photon_sigmaietaieta_endcap("Photon_sigma_ietaieta_endcap", "#sigmai#etai#eta(endcap)", 0., 0.03, 10);
	Variable photon_rhocorrchargediso_barrel("Photon_RhoCorrectedPFChargedHadronIso_barrel", "RhoCorrPFChargedHadronIso(barrel)", 0., 10., 2);
	Variable photon_rhocorrchargediso_endcap("Photon_RhoCorrectedPFChargedHadronIso_endcap", "RhoCorrPFChargedHadronIso(endcap)", 0., 10., 2);
	Variable photon_chargediso_barrel("Photon_PFChargedHadronIso_barrel", "PFChargedHadronIso(barrel)", 0., 10., 2);
	Variable photon_chargediso_endcap("Photon_PFChargedHadronIso_endcap", "PFChargedHadronIso(endcap)", 0., 10., 2);
	Variable photon_rhocorrneutraliso_barrel("Photon_RhoCorrectedPFNeutralHadronIso_barrel", "RhoCorrPFNeutralHadronIso(barrel)", 0., 10., 2);
	Variable photon_rhocorrneutraliso_endcap("Photon_RhoCorrectedPFNeutralHadronIso_endcap", "RhoCorrPFNeutralHadronIso(endcap)", 0., 10., 2);	
	Variable photon_neutraliso_barrel("Photon_PFNeutralHadronIso_barrel", "PFNeutralHadronIso(barrel)", 0., 10., 2);
	Variable photon_neutraliso_endcap("Photon_PFNeutralHadronIso_endcap", "PFNeutralHadronIso(endcap)", 0., 10., 2);   
	Variable photon_rhocorrphotoniso_barrel("Photon_RhoCorrectedPFPhotonIso_barrel", "RhoCorrPFPhotonIso(barrel)", 0., 10., 2);
	Variable photon_rhocorrphotoniso_endcap("Photon_RhoCorrectedPFPhotonIso_endcap", "RhoCorrPFPhotonIso(endcap)", 0., 10., 2);
	Variable photon_photoniso_barrel("Photon_PFPhotonIso_barrel", "PFPhotonIso(barrel)", 0., 10., 2);
	Variable photon_photoniso_endcap("Photon_PFPhotonIso_endcap", "PFPhotonIso(endcap)", 0., 10., 2);
	Variable photon_htowoe("Photon_HtowoE", "H/E", 0., 5., 2);
	Variable photon_numberofphotons("Number_Of_Photons", "N(#gamma)", -0.5, 6.5, 1);
	
	Variable photon_SCFRChIso_barrel("Photon_SCChIso_barrel", "SCFR Charged Hadron Iso (barrel)", 0, 110, 2);
	Variable photon_SCFRNuIso_barrel("Photon_SCNuIso_barrel", "SCFR Neutral Hadron Iso (barrel)", 0, 35, 2);
	Variable photon_SCFRPhIso_barrel("Photon_SCPhIso_barrel", "SCFR Photon Iso (barrel)", 0, 130, 2);
	Variable photon_SCFRChIso("Photon_SCChIso", "Events", 0, 110, 2);
	Variable photon_SCFRNuIso("Photon_SCNuIso", "Events", 0, 35, 2);
	Variable photon_SCFRPhIso("Photon_SCPhIso", "Events", 0, 130, 2);
	Variable photon_rhoCorrSCFRChIso_barrel("Photon_RhoCorrectedSCChIso_barrel", "Events", -5, 20, 1);
	Variable photon_rhoCorrSCFRNuIso_barrel("Photon_RhoCorrectedSCNuIso_barrel", "Events", -5, 20, 1);
	Variable photon_rhoCorrSCFRPhIso_barrel("Photon_RhoCorrectedSCPhIso_barrel", "Events", -5, 20, 1);
	Variable photon_rhoCorrSCFRChIso("Photon_RhoCorrectedSCChIso", "Events", -5, 20, 1);
	Variable photon_rhoCorrSCFRNuIso("Photon_RhoCorrectedSCNuIso", "Events", -5, 20, 1);
	Variable photon_rhoCorrSCFRPhIso("Photon_RhoCorrectedSCPhIso", "Events", -5, 20, 1);
	Variable photon_RandConeChIso("Photon_RandConeChIso", "Events", -5, 20, 1);
	Variable photon_RandConeNuIso("Photon_RandConeNuIso", "Events", -5, 20, 1);
	Variable photon_RandConePhIso("Photon_RandConePhIso", "Events", -5, 20, 1);
	Variable photon_RandConeChIso_barrel("Photon_RandConeChIso_barrel", "Events", -5, 20, 1);
	Variable photon_RandConeNuIso_barrel("Photon_RandConeNuIso_barrel", "Events", -5, 20, 1);
	Variable photon_RandConePhIso_barrel("Photon_RandConePhIso_barrel", "Events", -5, 20, 1);
	Variable photon_deltaRgammaJets("Photon_deltaR_jets", "#DeltaR(#gamma, jets)", 0, 5, 2);
	Variable photon_deltaRgammaElectrons("Photon_deltaR_electrons", "#DeltaR(#gamma, e)", 0, 5, 2);
	Variable photon_deltaRgammaMuons("Photon_deltaR_muons", "#DeltaR(#gamma, #mu)", 0, 5, 2);
	//Variable2D photon_abcdCHIsoVSsigmaiEtaiEta("RhoCorrectedSCFRChIso_v._Sigma_ietaieta", "RhoCorrectedSCFRChIso", "Sigma_ietaieta", 0, 20, 2, 0, 0.1);	
	Variable photon_sigmaietaieta_bkgd("Photon_sigma_ietaieta_barrel_background", "#sigmai#etai#eta (bkgd)", 0, 0.025, 10);

	setSelectionAndChannel("TTbarDiLeptonAnalysis", "MuMu");
	setPhotonSel("AllPhotons");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
	savePlot(samples, photon_sigmaietaieta_barrel);
	savePlot(samples, photon_sigmaietaieta_endcap);
	savePlot(samples, photon_rhocorrchargediso_barrel);
	savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
	savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
 	savePlot(samples, photon_SCFRNuIso_barrel);
 	savePlot(samples, photon_SCFRPhIso_barrel);
 	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
	SignalComparison(samples, photon_RandConeChIso_barrel);
	
	photon_sigmaietaieta_endcap.rebinFact *= 2;
	
	setChannel("EE");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
	savePlot(samples, photon_sigmaietaieta_barrel);
	savePlot(samples, photon_sigmaietaieta_endcap);
	savePlot(samples, photon_rhocorrchargediso_barrel);
	savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
	savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

	setChannel("EMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
	savePlot(samples, photon_sigmaietaieta_barrel);
	savePlot(samples, photon_sigmaietaieta_endcap);
	savePlot(samples, photon_rhocorrchargediso_barrel);
	savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
	savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

	photon_pt.rebinFact *= 2;
	photon_eta.rebinFact *= 2;

	setSelectionAndChannel("TTbarPhotonAnalysis", "MuMu");
	setPhotonSel("SignalPhotons");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

//	photon_sigmaietaieta_barrel->Integral();
	
	photon_abseta.rebinFact *= 2;
	photon_sigmaietaieta_barrel.rebinFact *= 2;
//	photon_sigmaietaieta_endcap.rebinFact *= 2;
	photon_deltaRgammaJets.rebinFact *= 10;
	photon_deltaRgammaElectrons.rebinFact *= 2;
	photon_deltaRgammaMuons.rebinFact *= 2;
	photon_RandConeChIso.rebinFact *= 2;
	photon_RandConeNuIso.rebinFact *= 2;
	photon_RandConePhIso.rebinFact *= 2;
	photon_rhoCorrSCFRChIso_barrel.rebinFact *= 2;
	photon_rhoCorrSCFRNuIso_barrel.rebinFact *= 2;
	photon_rhoCorrSCFRPhIso_barrel.rebinFact *= 2;
	

	setChannel("EE");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);


	setChannel("EMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);


	setPhotonSel("NminusOnePhotons");
	setChannel("MuMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
//        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
//	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
//	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
//	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
//	savePlot(samples, photon_deltaRgammaJets);
//	savePlot(samples, photon_deltaRgammaElectrons);
//	savePlot(samples, photon_deltaRgammaMuons);
	savePlot(samples, photon_sigmaietaieta_bkgd);

	setChannel("EE");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
//        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
//	savePlot(samples, photon_deltaRgammaJets);
//	savePlot(samples, photon_deltaRgammaElectrons);
//	savePlot(samples, photon_deltaRgammaMuons);
        savePlot(samples, photon_sigmaietaieta_bkgd);

	setChannel("EMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
//        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
//	savePlot(samples, photon_deltaRgammaJets);
//	savePlot(samples, photon_deltaRgammaElectrons);
//	savePlot(samples, photon_deltaRgammaMuons);
	savePlot(samples, photon_sigmaietaieta_bkgd);
	
	setSelectionAndChannel("TTbarLooseSelectionAnalysis", "MuMu");
	setPhotonSel("AllPhotons");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
	savePlot(samples, photon_sigmaietaieta_barrel);
	savePlot(samples, photon_sigmaietaieta_endcap);
	savePlot(samples, photon_rhocorrchargediso_barrel);
	savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
	savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
 	savePlot(samples, photon_SCFRNuIso_barrel);
 	savePlot(samples, photon_SCFRPhIso_barrel);
 	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
	SignalComparison(samples, photon_RandConeChIso_barrel);
	
	photon_sigmaietaieta_endcap.rebinFact *= 2;
	
	setChannel("EE");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
	savePlot(samples, photon_sigmaietaieta_barrel);
	savePlot(samples, photon_sigmaietaieta_endcap);
	savePlot(samples, photon_rhocorrchargediso_barrel);
	savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
	savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

	setChannel("EMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
	savePlot(samples, photon_sigmaietaieta_barrel);
	savePlot(samples, photon_sigmaietaieta_endcap);
	savePlot(samples, photon_rhocorrchargediso_barrel);
	savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
	savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

	photon_pt.rebinFact *= 2;
	photon_eta.rebinFact *= 2;
	
	setPhotonSel("SignalPhotons");
        setChannel("MuMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
	savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

//	photon_sigmaietaieta_barrel->Integral();
	
	photon_abseta.rebinFact *= 2;
	photon_sigmaietaieta_barrel.rebinFact *= 2;
//	photon_sigmaietaieta_endcap.rebinFact *= 2;
	photon_deltaRgammaJets.rebinFact *= 10;
	photon_deltaRgammaElectrons.rebinFact *= 2;
	photon_deltaRgammaMuons.rebinFact *= 2;
	photon_RandConeChIso.rebinFact *= 2;
	photon_RandConeNuIso.rebinFact *= 2;
	photon_RandConePhIso.rebinFact *= 2;
	photon_rhoCorrSCFRChIso_barrel.rebinFact *= 2;
	photon_rhoCorrSCFRNuIso_barrel.rebinFact *= 2;
	photon_rhoCorrSCFRPhIso_barrel.rebinFact *= 2;
	

	setChannel("EE");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);

	setChannel("EMu");
	savePlot(samples, photon_pt);
	savePlot(samples, photon_eta);
        savePlot(samples, photon_abseta);
        savePlot(samples, photon_sigmaietaieta_barrel);
        savePlot(samples, photon_sigmaietaieta_endcap);
        savePlot(samples, photon_rhocorrchargediso_barrel);
        savePlot(samples, photon_rhocorrchargediso_endcap);
	savePlot(samples, photon_chargediso_barrel);
	savePlot(samples, photon_chargediso_endcap);
	savePlot(samples, photon_rhocorrneutraliso_barrel);
	savePlot(samples, photon_rhocorrneutraliso_endcap);
	savePlot(samples, photon_neutraliso_barrel);
	savePlot(samples, photon_neutraliso_endcap);
	savePlot(samples, photon_rhocorrphotoniso_barrel);
	savePlot(samples, photon_rhocorrphotoniso_endcap);
	savePlot(samples, photon_photoniso_barrel);
	savePlot(samples, photon_photoniso_endcap);
	savePlot(samples, photon_htowoe);
        savePlot(samples, photon_numberofphotons);
	savePlot(samples, photon_SCFRChIso_barrel);
	savePlot(samples, photon_SCFRNuIso_barrel);
	savePlot(samples, photon_SCFRPhIso_barrel);
	savePlot(samples, photon_SCFRChIso);
	savePlot(samples, photon_SCFRNuIso);
	savePlot(samples, photon_SCFRPhIso);
	savePlot(samples, photon_rhoCorrSCFRChIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRNuIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRPhIso_barrel);
	savePlot(samples, photon_rhoCorrSCFRChIso);
	savePlot(samples, photon_rhoCorrSCFRNuIso);
	savePlot(samples, photon_rhoCorrSCFRPhIso);
	savePlot(samples, photon_RandConeChIso);
	savePlot(samples, photon_RandConeNuIso);
	savePlot(samples, photon_RandConePhIso);
	savePlot(samples, photon_RandConeChIso_barrel);
	savePlot(samples, photon_RandConeNuIso_barrel);
	savePlot(samples, photon_RandConePhIso_barrel);
	savePlot(samples, photon_deltaRgammaJets);
	savePlot(samples, photon_deltaRgammaElectrons);
	savePlot(samples, photon_deltaRgammaMuons);
        SignalComparison(samples, photon_RandConeChIso_barrel);
}

void Photons::allPlots2D(AllSamples2D samples) {

	Variable2D photon_abcdCHIsoVSsigmaiEtaiEta("RhoCorrectedSCFRChIso_v._Sigma_ietaieta", "RhoCorrectedSCFRChIso", "Sigma_ietaieta", 0, 20, 2, 0, 0.1);	

	setSelectionAndChannel("TTbarPhotonAnalysis", "MuMu");
        setPhotonSel("SignalPhotons");

	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);

	setChannel("EE");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);

	setChannel("EMu");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);	

        setSelectionAndChannel("TTbarLooseSelectionAnalysis", "MuMu");
        setPhotonSel("AllPhotons");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);
	
	setChannel("EE");
        savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);

	setChannel("EMu");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);	
	
	setPhotonSel("SignalPhotons");
        setChannel("MuMu");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);

        setChannel("EE");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);
	
        setChannel("EMu");
	savePlot2D(samples, photon_abcdCHIsoVSsigmaiEtaiEta);
}

void Photons::setPhotonSel(TString photon_sel){
	objName = "Photons/"+photon_sel;
}

} /* namespace std */
